Lag ny pakke for PageGenerator, renaming fra FormGenerator
domstolene/designsystem pull request #631
Opened 2023-02-21 07:41 UTC by oivindjenssen

2023-02-21 14:00 UTC, petter commented
Fint om funksjonene kunne brukt camelCase istedenfor PascalCase sånn at det er mer likt som resten av designsystemet 😊

2023-02-22 12:26 UTC, oivindjenssen commented
> Fint om funksjonene kunne brukt camelCase istedenfor PascalCase sånn at det er mer likt som resten av designsystemet 😊

Fixed nå.

2023-02-22 13:50 UTC, trondkla approved these changes
Solid stykke arbeid 👌

2023-02-22 13:50 UTC, trondkla commented on packages/page-generator/src/helpers/addFieldToState.tsx
> +      key = field.props.name || field.props.id || 'FIELD_MISSING_NAME_OR_ID';
Burde ikke field_missing_name vært en konstant?

2023-02-23 07:24 UTC, oivindjenssen commented on packages/page-generator/src/helpers/addFieldToState.tsx
> +      key = field.props.name || field.props.id || 'FIELD_MISSING_NAME_OR_ID';
Fixed

2023-02-24 11:44 UTC, petter reviewed
Skulle vi fjernet `FormGenerator` fra `dds-components` samtidig? Eller i det minste markere den med `@deprecated`.

2023-02-24 12:00 UTC, oivindjenssen commented
> Skulle vi fjernet `FormGenerator` fra `dds-components` samtidig? Eller i det minste markere den med `@deprecated`. Hvis den slettes så husk å også fjerne referansen til den fra README

@petter Yes, god ide. har markert som deprecated nå.

2023-02-24 15:05 UTC, petter requested changes

2023-02-24 15:05 UTC, petter commented on packages/page-generator/src/components/PageGenerator.tsx
> +export const PageGenerator = (props: PageGeneratorProps) => {
Fint om du legger inn litt JSDoc på `PageGenerator` og `SectionGenerator` om hva de gjør og hvordan de er forskjellige.

2023-02-27 08:18 UTC, oivindjenssen commented on packages/page-generator/package.json
> +    "styled-components": "^5"
Ligger under `@types/styled-components`. (Så hvordan det lå i `dds-components` og gjorde likt der..)

2023-02-27 08:38 UTC, oivindjenssen commented on packages/page-generator/src/helpers/addFieldToState.tsx
> +  let key = '';
I casen med Select er det `field.name`. 

Ser at når jeg flytter ut key'en fra de andre casene, får jeg type feil, siden `name` ikke eksisterer under `field.props` for CheckboxGroup og ToggleButtonGroup.

Tror det kan bli mer kode for å sette `key` penere, istedenfor duplisering i dette tilfelle..

2023-02-27 09:15 UTC, oivindjenssen commented on .changeset/thirty-buses-mate.md
> +Legg til ny pakke `dds-page-generator` og eksporter getBaseHTMLProps og ScreenSize Utils fra `dds-components`
Fixed

2023-02-27 09:15 UTC, oivindjenssen commented on packages/page-generator/README.md
> +Tekstformatering til bruk i domstolenes tjenester.
Ooops.. Fixed.

2023-02-27 09:16 UTC, oivindjenssen commented on packages/page-generator/package.json
> +    "test:watch": "jest watch",
Tja, kan prøve på nytt med vitest. Møtte noen problemer da jeg måtte sette opp `jsdom` environment mens jeg trøbla med bygging.. kan gi det et nytt forsøk!

2023-02-27 09:16 UTC, oivindjenssen commented on packages/components/src/components/FormGenerator/FormGenerator.tsx
> + * @deprecated FormGenerator er flyttet til egen pakke og renamet til PageGenerator. Se packages/page-generator.
Fixed.

2023-02-27 09:17 UTC, oivindjenssen commented on packages/page-generator/src/components/PageGenerator.tsx
> +    }
Fixed

2023-02-27 09:17 UTC, oivindjenssen commented on packages/page-generator/src/components/SectionGenerator.tsx
> +    }
Fixed.

2023-02-27 09:17 UTC, oivindjenssen commented on packages/page-generator/src/tests/PageGenerator.spec.tsx
> +    expect(updatedValue).toEqual(expectedValue);
Fixed.

2023-02-27 09:18 UTC, oivindjenssen commented on packages/page-generator/src/components/PageGenerator.tsx
> +export const PageGenerator = (props: PageGeneratorProps) => {
Fixed, la på litt dokumentasjon nå. La på en beskrivelse om hva de selv gjør, ikke hva de ikke gjør...

2023-02-27 11:49 UTC, petter commented on packages/page-generator/package.json
> +    "styled-components": "^5"
`@types/styled-components` inneholder bare typene for `styled-components`, ikke noe av implementasjon. Nå får vi `styled-components` fra `babel-plugin-styled-components` fra `dds-components` som gjør at vi ikke har helt kontroll på hvilken `styled-components` versjon som blir brukt under utvikling. Var ikke klar over at det også manglet i `dds-components`, det burde vi nok også fikse opp i, men trenger ikke å gjøre det i denne PR-en.

2023-02-28 11:36 UTC, oivindjenssen commented on packages/page-generator/package.json
> +    "styled-components": "^5"
Fixed.

2023-02-28 12:22 UTC, oivindjenssen commented on packages/page-generator/package.json
> +    "test:watch": "jest watch",
Byttet til vitest nå. Litt fram og tilbake, men får kjørt tester lokalt og bygget.

2023-03-01 12:24 UTC, merged