Add textarea to generator
domstolene/designsystem pull request #919
Opened 2023-10-03 08:27 UTC by trondkla

Adds text area to page and section generator

2023-10-03 10:20 UTC, trondkla commented
Har prøvd å slette package-lock.json og lage den på nytt, men den blir gigastor -.-

2023-10-03 10:23 UTC, trondkla commented on packages/page-generator/src/components/SectionGenerator.tsx
> +  const textAreaOnChange = <T extends HTMLTextAreaElement>(event: ChangeEvent<T>) => {
TextArea har ikke checked attributttet, så var pain å kombinere fieldOnChange og textAreaOnChange, er det greit nok med to?

2023-10-03 10:24 UTC, trondkla commented on packages/page-generator/src/storybook/FormFields.tsx
> +        ],
Denne var bare for å teste nøstede validering. Er litt tullete, men det er også omg, så lar den ligge :)

2023-10-03 10:45 UTC, trondkla commented on packages/page-generator/src/components/SectionGenerator.tsx
> +  const textAreaOnChange = <T extends HTMLTextAreaElement>(event: ChangeEvent<T>) => {
Tar gjerne imot forslag til løsning hvis det ønskes å kombinere de :)

2023-10-03 12:00 UTC, oivindjenssen requested changes

2023-10-03 12:00 UTC, oivindjenssen commented on packages/page-generator/src/components/PageGenerator.tsx
> +  const textAreaOnChange = <T extends HTMLTextAreaElement>(
Burde kanskje nullstilt errorMessage her også, slik at det blir konsekvent med TextInput og TextArea.

2023-10-03 12:13 UTC, petter commented
Gjerne rydd litt i commit-history, evt squash merge

2023-10-03 12:51 UTC, petter commented on packages/components/src/components/Modal/Modal.spec.tsx
> +
Dette kan kanskje heller inn i `setupTests.ts`

2023-10-03 12:51 UTC, petter commented on packages/page-generator/src/components/PageGenerator.tsx
> +      (field as FieldWithValidations).props.errorMessage = errorMessage;
Denne casten er ikke nødvendig da vi har en cast i `isFieldWithValidations`

```suggestion
      field.props.errorMessage = errorMessage;
```

2023-10-03 14:01 UTC, trondkla commented on packages/page-generator/src/components/PageGenerator.tsx
> +    if (!fieldsToSearch) {
Ja, det var pga rekursiviteten av funksjonen. Er ikke garantert at alle rows har fields teknisk sett. Men nå har jeg flyttet sjekken til før den kaller metoden :)

2023-10-03 14:01 UTC, trondkla commented on packages/page-generator/src/components/PageGenerator.tsx
> +  const textAreaOnChange = <T extends HTMLTextAreaElement>(
Jeg fikk forenklet denne :)

2023-10-03 14:04 UTC, trondkla commented on packages/components/src/components/Modal/Modal.spec.tsx
> +
Godt tips!

2023-10-03 14:06 UTC, trondkla commented on packages/page-generator/src/components/PageGenerator.tsx
> +      (field as FieldWithValidations).props.errorMessage = errorMessage;
Bra spotta! Var en rewrite som hang igjen :)

2023-10-03 14:07 UTC, trondkla commented on packages/page-generator/src/components/SectionGenerator.tsx
> +  const textAreaOnChange = <T extends HTMLTextAreaElement>(event: ChangeEvent<T>) => {
Fikk forenkla den

2023-10-04 05:40 UTC, oivindjenssen requested changes

2023-10-04 05:40 UTC, oivindjenssen commented on packages/page-generator/src/components/PageGenerator.tsx
> +      if (
Kan bruke `isPageGeneratorRow` her

2023-10-04 07:44 UTC, petter approved these changes
Flott at du fikk fjernet den `textareaOnChange` 🤩

2023-10-06 09:58 UTC, trondkla commented on packages/page-generator/src/components/PageGenerator.tsx
> +      if (
Nice!

2023-10-06 10:30 UTC, oivindjenssen approved these changes

2023-10-06 13:29 UTC, merged